// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: grape/api/confd/apiserver.proto

package confd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	core "grape/api/core"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grape_api_confd_apiserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grape_api_confd_apiserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_grape_api_confd_apiserver_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type DelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grape_api_confd_apiserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grape_api_confd_apiserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_grape_api_confd_apiserver_proto_rawDescGZIP(), []int{1}
}

func (x *DelRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_grape_api_confd_apiserver_proto protoreflect.FileDescriptor

var file_grape_api_confd_apiserver_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x64, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x64, 0x1a, 0x1b, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x64,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x32, 0xc2, 0x01,
	0x0a, 0x09, 0x41, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x03, 0x53,
	0x65, 0x74, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x1a, 0x15, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x64, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x61, 0x70,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x1b, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x64, 0x2e, 0x44,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x61, 0x70,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x63, 0x6f, 0x6e, 0x66, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grape_api_confd_apiserver_proto_rawDescOnce sync.Once
	file_grape_api_confd_apiserver_proto_rawDescData = file_grape_api_confd_apiserver_proto_rawDesc
)

func file_grape_api_confd_apiserver_proto_rawDescGZIP() []byte {
	file_grape_api_confd_apiserver_proto_rawDescOnce.Do(func() {
		file_grape_api_confd_apiserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_grape_api_confd_apiserver_proto_rawDescData)
	})
	return file_grape_api_confd_apiserver_proto_rawDescData
}

var file_grape_api_confd_apiserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grape_api_confd_apiserver_proto_goTypes = []interface{}{
	(*GetRequest)(nil), // 0: grape.api.confd.GetRequest
	(*DelRequest)(nil), // 1: grape.api.confd.DelRequest
	(*Configs)(nil),    // 2: grape.api.confd.Configs
	(*core.Empty)(nil), // 3: grape.api.core.Empty
}
var file_grape_api_confd_apiserver_proto_depIdxs = []int32{
	2, // 0: grape.api.confd.ApiServer.Set:input_type -> grape.api.confd.Configs
	0, // 1: grape.api.confd.ApiServer.Get:input_type -> grape.api.confd.GetRequest
	1, // 2: grape.api.confd.ApiServer.Del:input_type -> grape.api.confd.DelRequest
	3, // 3: grape.api.confd.ApiServer.Set:output_type -> grape.api.core.Empty
	2, // 4: grape.api.confd.ApiServer.Get:output_type -> grape.api.confd.Configs
	3, // 5: grape.api.confd.ApiServer.Del:output_type -> grape.api.core.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grape_api_confd_apiserver_proto_init() }
func file_grape_api_confd_apiserver_proto_init() {
	if File_grape_api_confd_apiserver_proto != nil {
		return
	}
	file_grape_api_confd_config_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grape_api_confd_apiserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grape_api_confd_apiserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grape_api_confd_apiserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grape_api_confd_apiserver_proto_goTypes,
		DependencyIndexes: file_grape_api_confd_apiserver_proto_depIdxs,
		MessageInfos:      file_grape_api_confd_apiserver_proto_msgTypes,
	}.Build()
	File_grape_api_confd_apiserver_proto = out.File
	file_grape_api_confd_apiserver_proto_rawDesc = nil
	file_grape_api_confd_apiserver_proto_goTypes = nil
	file_grape_api_confd_apiserver_proto_depIdxs = nil
}
