services:
  etcd:
    image: bitnami/etcd
    environment:
    - ALLOW_NONE_AUTHENTICATION=yes
    ports:
    - 2379:2379
    networks:
      grape:

  controller:
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
    volumes:
    - ./bootstrap.yaml:/goworker/bootstrap.yaml
    ports:
    - 15010:15010
    command: controller s
    links:
    - etcd
    networks:
      grape:

  discovery:
    build:
      context: .
      dockerfile: docker/Dockerfile.discovery
    volumes:
    - ./bootstrap.yaml:/goworker/bootstrap.yaml
    links:
    - etcd
    ports:
    - 15020:15020
    networks:
      grape:
    
  confd:
    build:
      context: .
      dockerfile: docker/Dockerfile.testapp
    command: confd -a discovery:15020 -p demo/order -g order-demo-v1 -d -r top
    depends_on:
    - discovery
    networks:
      grape:

networks:
  grape:
    name: grape
    # external:
    #   name: grape