// Code generated by "stringer -type ServiceProtocol -trimprefix PROTOCOL_ -output service_protocol_str.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PROTOCOL_HTTP-0]
	_ = x[PROTOCOL_HTTPS-1]
	_ = x[PROTOCOL_HTTP2-2]
	_ = x[PROTOCOL_TCP-3]
	_ = x[PROTOCOL_UDP-4]
	_ = x[PROTOCOL_TLS-5]
	_ = x[PROTOCOL_GRPC-6]
}

const _ServiceProtocol_name = "HTTPHTTPSHTTP2TCPUDPTLSGRPC"

var _ServiceProtocol_index = [...]uint8{0, 4, 9, 14, 17, 20, 23, 27}

func (i ServiceProtocol) String() string {
	if i < 0 || i >= ServiceProtocol(len(_ServiceProtocol_index)-1) {
		return "ServiceProtocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceProtocol_name[_ServiceProtocol_index[i]:_ServiceProtocol_index[i+1]]
}
