// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package view

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	core "grape/api/v1/core"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiServerClient is the client API for ApiServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiServerClient interface {
	Set(ctx context.Context, in *ServiceLogs, opts ...grpc.CallOption) (*core.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ServiceLogs, error)
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*core.Empty, error)
}

type apiServerClient struct {
	cc grpc.ClientConnInterface
}

func NewApiServerClient(cc grpc.ClientConnInterface) ApiServerClient {
	return &apiServerClient{cc}
}

func (c *apiServerClient) Set(ctx context.Context, in *ServiceLogs, opts ...grpc.CallOption) (*core.Empty, error) {
	out := new(core.Empty)
	err := c.cc.Invoke(ctx, "/grape.api.v1.view.ApiServer/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServerClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ServiceLogs, error) {
	out := new(ServiceLogs)
	err := c.cc.Invoke(ctx, "/grape.api.v1.view.ApiServer/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServerClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*core.Empty, error) {
	out := new(core.Empty)
	err := c.cc.Invoke(ctx, "/grape.api.v1.view.ApiServer/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServerServer is the server API for ApiServer service.
// All implementations must embed UnimplementedApiServerServer
// for forward compatibility
type ApiServerServer interface {
	Set(context.Context, *ServiceLogs) (*core.Empty, error)
	Get(context.Context, *GetRequest) (*ServiceLogs, error)
	Del(context.Context, *DelRequest) (*core.Empty, error)
	mustEmbedUnimplementedApiServerServer()
}

// UnimplementedApiServerServer must be embedded to have forward compatible implementations.
type UnimplementedApiServerServer struct {
}

func (UnimplementedApiServerServer) Set(context.Context, *ServiceLogs) (*core.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedApiServerServer) Get(context.Context, *GetRequest) (*ServiceLogs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedApiServerServer) Del(context.Context, *DelRequest) (*core.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedApiServerServer) mustEmbedUnimplementedApiServerServer() {}

// UnsafeApiServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServerServer will
// result in compilation errors.
type UnsafeApiServerServer interface {
	mustEmbedUnimplementedApiServerServer()
}

func RegisterApiServerServer(s grpc.ServiceRegistrar, srv ApiServerServer) {
	s.RegisterService(&ApiServer_ServiceDesc, srv)
}

func _ApiServer_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceLogs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServerServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grape.api.v1.view.ApiServer/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServerServer).Set(ctx, req.(*ServiceLogs))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiServer_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grape.api.v1.view.ApiServer/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServerServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiServer_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServerServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grape.api.v1.view.ApiServer/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServerServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiServer_ServiceDesc is the grpc.ServiceDesc for ApiServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grape.api.v1.view.ApiServer",
	HandlerType: (*ApiServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _ApiServer_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ApiServer_Get_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _ApiServer_Del_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grape/api/v1/view/view.proto",
}

// DiscoveryServerClient is the client API for DiscoveryServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryServerClient interface {
	StreamLogs(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (DiscoveryServer_StreamLogsClient, error)
}

type discoveryServerClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServerClient(cc grpc.ClientConnInterface) DiscoveryServerClient {
	return &discoveryServerClient{cc}
}

func (c *discoveryServerClient) StreamLogs(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (DiscoveryServer_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DiscoveryServer_ServiceDesc.Streams[0], "/grape.api.v1.view.DiscoveryServer/StreamLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &discoveryServerStreamLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DiscoveryServer_StreamLogsClient interface {
	Recv() (*AllLogs, error)
	grpc.ClientStream
}

type discoveryServerStreamLogsClient struct {
	grpc.ClientStream
}

func (x *discoveryServerStreamLogsClient) Recv() (*AllLogs, error) {
	m := new(AllLogs)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DiscoveryServerServer is the server API for DiscoveryServer service.
// All implementations must embed UnimplementedDiscoveryServerServer
// for forward compatibility
type DiscoveryServerServer interface {
	StreamLogs(*DiscoveryRequest, DiscoveryServer_StreamLogsServer) error
	mustEmbedUnimplementedDiscoveryServerServer()
}

// UnimplementedDiscoveryServerServer must be embedded to have forward compatible implementations.
type UnimplementedDiscoveryServerServer struct {
}

func (UnimplementedDiscoveryServerServer) StreamLogs(*DiscoveryRequest, DiscoveryServer_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedDiscoveryServerServer) mustEmbedUnimplementedDiscoveryServerServer() {}

// UnsafeDiscoveryServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServerServer will
// result in compilation errors.
type UnsafeDiscoveryServerServer interface {
	mustEmbedUnimplementedDiscoveryServerServer()
}

func RegisterDiscoveryServerServer(s grpc.ServiceRegistrar, srv DiscoveryServerServer) {
	s.RegisterService(&DiscoveryServer_ServiceDesc, srv)
}

func _DiscoveryServer_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiscoveryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscoveryServerServer).StreamLogs(m, &discoveryServerStreamLogsServer{stream})
}

type DiscoveryServer_StreamLogsServer interface {
	Send(*AllLogs) error
	grpc.ServerStream
}

type discoveryServerStreamLogsServer struct {
	grpc.ServerStream
}

func (x *discoveryServerStreamLogsServer) Send(m *AllLogs) error {
	return x.ServerStream.SendMsg(m)
}

// DiscoveryServer_ServiceDesc is the grpc.ServiceDesc for DiscoveryServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grape.api.v1.view.DiscoveryServer",
	HandlerType: (*DiscoveryServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _DiscoveryServer_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grape/api/v1/view/view.proto",
}
