apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
  generation: 2
  labels:
    app: grape-injector
  name: grape-injector
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMRENDQWhTZ0F3SUJBZ0lSQU8zQ3lRaEd6WFZQdS9DRWVIVTI2bXd3RFFZSktvWklodmNOQVFFTEJRQXcKRWpFUU1BNEdBMVVFQ2hNSFFXTnRaU0JEYnpBZ0Z3MDNNREF4TURFd01EQXdNREJhR0E4eU1EZzBNREV5T1RFMgpNREF3TUZvd0VqRVFNQTRHQTFVRUNoTUhRV050WlNCRGJ6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFMLzhoNjNJQStwQVNkVWpmdnovQmZBTkloRUo5bGtkdkM0c1VpUWcxdm1nS2VTZHF3YzgKRWYwRExDTzRoZS9jWWtGRWhIa2Q1dFRYa3Vtb3YwdmtWbHpPbTZMeFFuNWN6WTRXZE1TRVdPdnp3bGZFdWFuMApvR1U4OUtnVEpKcURsUkJ3SmVWNDFXK05mbEhnS1ZUVk1uL1Q2QVVNL0V1K2FCUVhnTkc2eDRxdWZCZ1J5SlZ6CjNXMkZYS3kvWk93VStSQWdHOG5Ic081Snh0ZEZZL005NmpJZnNBeFl2RGs3ZXFRK2czcXFLQlVzNFNvcjV1YVQKL29jcXk3dzk3bjR0blhFM3JNc2xlZjRseXhIZU1YM25LajdzRm90UWViNmFkcG1kUFVDWDBtTENYYlA1ZE00RgpMWVlKaDR4ZWNXWnlyWFlQWWxNaC9PTnV5azZ1aC9kaDhMY0NBd0VBQWFON01Ia3dEZ1lEVlIwUEFRSC9CQVFECkFnS2tNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME8KQkJZRUZNVnA4VmdDUkdtRXZKZWZNVHJpUlJVQ3Fsa1BNQ0lHQTFVZEVRUWJNQm1DRjJkeVlYQmxaQzVuY21GdwpaUzF6ZVhOMFpXMHVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDc2RhaEhtL3FrcE54b0oyalZicGRCCk14MDNBWnBBMHVWbzlzNDVCbnZDUmtQbmR4Mk1DWkQzZ0JhaVJIZHc4N1YycGhHalN2eTZzU2J5YjV6dEZYTHQKd0xDR05wSkszSHhobGh1WXk1aU01NmQzeG04Slh4TlBQeXJlcmM5dWtmZmtNM3RkcjB6RlNnd2UvV1VES0l6TgpMRkpjMGxtbzRoQ28rWk5hR3pwb0hweElKNGVzR3BmT2dEUmJzQkdLUCs2cXN0SjdZSmNTN1Rtc2Q1SnB4ZGpqCk1zYXBKeXIydk5UZis3bDQvTTRQNytLNEZ4cmIxbzN3K2VvcGFlZERtQVRhUDRBT2lIMHloSE9KS0d5VHFzMHIKZGxnL1ZTeXlQTmovQi9Pc0dJSDRKb0RHdjF2aHlhc3hhRE1PYXNrZExDRkhoaXhnY3IyOHBpTWdWamJZcElsaQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: graped
      namespace: grape-system
      path: /inject
      port: 8082
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: pod.injector.grape
  # namespaceSelector:
  #   matchExpressions:
  #   - key: nt-injection
  #     operator: In
  #     values:
  #     - "true"
  objectSelector:
    matchExpressions:
    - key: grape/injection
      operator: In
      values:
      # - "true"
      - "enable"
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10