apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
  generation: 2
  labels:
    app: grape-injector
  name: grape-injector
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lSQUxzYzNMcGhJSFpQWUpheFFHUXRzK1l3RFFZSktvWklodmNOQVFFTEJRQXcKRWpFUU1BNEdBMVVFQ2hNSFFXTnRaU0JEYnpBZ0Z3MDNNREF4TURFd01EQXdNREJhR0E4eU1EZzBNREV5T1RFMgpNREF3TUZvd0VqRVFNQTRHQTFVRUNoTUhRV050WlNCRGJ6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFPSHpJakdSRWFlSmwrbDRtMkVrUUV0eWtnc0hnaGcrcTd0VVMzYWNpa2U2cW04MkxmRnAKVzZWd2hHZVpZNHk0RXE2dTFiL1U3bTJrOGFvYjgwQjZvU09nZXFKUHd4VWFyclhhY0x4MW5yVWZsUzZYcUcyYgpxUVNkYklnNlBycmFSVndNeGt5NjczeXhnaEpyZU1QazYxb0I5bzR0bnVicjI5cjVRbXpPTDRod2t1L3FacWlpClpUSFJzdnE1NkxTcnpuOFlaVkhkeTRUR3duR0JzK2JyZWNxdFRFYWVoeTB2cjMxSHdmOHdEOXNuekJMZ09yT2cKa2VOdGp5N0QvT1BCU2VjaWZyRDFFN2lyYS96TVA0S1BQZktuVEgzdmlzaUo5RG5pZ3JvckVTTU9wWlR0Y1hLQQoreFkraThheHZ2L293RlcyTDhDWmtFUlFPZm1SRlNFT3ptY0NBd0VBQWFPQmhEQ0JnVEFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVU5ZFRoWXBEZVRSalR2VXNEMTFyem5SVjk1RkV3S2dZRFZSMFJCQ013SVlJZlozSmhjR1V0YVc1cQpaV04wYjNJdVozSmhjR1V0YzNsemRHVnRMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQU5XaHV3dXJsCjhCR2tTcXRnRzNRS0VjMWpmOUcxb0ZNZ1BoQTU4VDNWN083ckFHNTJBbC9IZUVVY0ljbTVxTmhFRytCU1NyVmgKQ2J2RUVCbTFaWVQrcVA2Zi9MMTdscEphSmNMRFh5TC9TZGF6Z2VCMWdhY1AvYVU4dmMwMk1VZTArMzJVTVBtcQpmTEF2SHNMQ2p2MXZtTisrZWJmbXh1cVBWUlF4L1h2K0hGekVEbUNDZ2xLVGl4bFYrUG9NZmlVTW1GYlFoQy9NCnBnZWM2Qk9JMmxQb3NRRy9WS1BoUGNGV1hQbm5temxNWGRpdk1oRWZ2LzZwOFF3ZXJBQTNTazN1enI4NldzOWkKU2d0TkFVLzlHUVp0ZWpPNzV5bklBMDZheHFqN1oyejZYZzNCdnV4UVBBK05OazVWUzJ5NTdvMXJEdTY1ZmNKaApkSysrd3RHNTRFS2M0dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: grape-injector
      namespace: grape-system
      path: /inject
      port: 8443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: pod.injector.grape
  namespaceSelector:
    matchExpressions:
    - key: grape/enable
      operator: In
      values:
      - "true"
  objectSelector:
    matchExpressions:
    - key: grape/enable
      operator: In
      values:
      - "true"
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10