---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grape-injector
  name: grape-injector
  namespace: grape-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grape-injector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grape-injector
    spec:
      containers:
      - image: repo.nexttao.com.cn/common/grape-injector:latest
        imagePullPolicy: Always
        name: grape-injector
        ports:
        - containerPort: 8443
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /goworker/bootstrap.yaml
          name: grape-config
          subPath: bootstrap.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: grape
      serviceAccountName: grape
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: grape-config
        name: grape-config
---
apiVersion: v1
kind: Service
metadata:
  name: grape-injector
  namespace: grape-system
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: grape-injector
  sessionAffinity: None
  type: ClusterIP