// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: grape/api/core/deploy.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// option (resource).type = "api.grape.deplsoy_group";
	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nodes []*Node `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *DeployGroup) Reset() {
	*x = DeployGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grape_api_core_deploy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployGroup) ProtoMessage() {}

func (x *DeployGroup) ProtoReflect() protoreflect.Message {
	mi := &file_grape_api_core_deploy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployGroup.ProtoReflect.Descriptor instead.
func (*DeployGroup) Descriptor() ([]byte, []int) {
	return file_grape_api_core_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *DeployGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployGroup) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_grape_api_core_deploy_proto protoreflect.FileDescriptor

var file_grape_api_core_deploy_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67,
	0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x1b, 0x67,
	0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x0b, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x72, 0x61,
	0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_grape_api_core_deploy_proto_rawDescOnce sync.Once
	file_grape_api_core_deploy_proto_rawDescData = file_grape_api_core_deploy_proto_rawDesc
)

func file_grape_api_core_deploy_proto_rawDescGZIP() []byte {
	file_grape_api_core_deploy_proto_rawDescOnce.Do(func() {
		file_grape_api_core_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(file_grape_api_core_deploy_proto_rawDescData)
	})
	return file_grape_api_core_deploy_proto_rawDescData
}

var file_grape_api_core_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grape_api_core_deploy_proto_goTypes = []interface{}{
	(*DeployGroup)(nil), // 0: grape.api.core.DeployGroup
	(*Node)(nil),        // 1: grape.api.core.Node
}
var file_grape_api_core_deploy_proto_depIdxs = []int32{
	1, // 0: grape.api.core.DeployGroup.nodes:type_name -> grape.api.core.Node
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grape_api_core_deploy_proto_init() }
func file_grape_api_core_deploy_proto_init() {
	if File_grape_api_core_deploy_proto != nil {
		return
	}
	file_grape_api_core_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grape_api_core_deploy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grape_api_core_deploy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grape_api_core_deploy_proto_goTypes,
		DependencyIndexes: file_grape_api_core_deploy_proto_depIdxs,
		MessageInfos:      file_grape_api_core_deploy_proto_msgTypes,
	}.Build()
	File_grape_api_core_deploy_proto = out.File
	file_grape_api_core_deploy_proto_rawDesc = nil
	file_grape_api_core_deploy_proto_goTypes = nil
	file_grape_api_core_deploy_proto_depIdxs = nil
}
