// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: grape/api/core/policy.proto

package core

import (
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Policy_Type int32

const (
	Policy_HealthCheck Policy_Type = 0
)

// Enum value maps for Policy_Type.
var (
	Policy_Type_name = map[int32]string{
		0: "HealthCheck",
	}
	Policy_Type_value = map[string]int32{
		"HealthCheck": 0,
	}
)

func (x Policy_Type) Enum() *Policy_Type {
	p := new(Policy_Type)
	*p = x
	return p
}

func (x Policy_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Policy_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_grape_api_core_policy_proto_enumTypes[0].Descriptor()
}

func (Policy_Type) Type() protoreflect.EnumType {
	return &file_grape_api_core_policy_proto_enumTypes[0]
}

func (x Policy_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Policy_Type.Descriptor instead.
func (Policy_Type) EnumDescriptor() ([]byte, []int) {
	return file_grape_api_core_policy_proto_rawDescGZIP(), []int{0, 0}
}

type Policy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// option (resource).type = "api.grape.policy";
	PolicyType Policy_Type `protobuf:"varint,1,opt,name=policy_type,json=policyType,proto3,enum=grape.api.core.Policy_Type" json:"policy_type,omitempty"`
	Policy     *any.Any    `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Name       string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Policy) Reset() {
	*x = Policy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grape_api_core_policy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_grape_api_core_policy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_grape_api_core_policy_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetPolicyType() Policy_Type {
	if x != nil {
		return x.PolicyType
	}
	return Policy_HealthCheck
}

func (x *Policy) GetPolicy() *any.Any {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HealthCheckPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// option (resource).type = "api.grape.health_check_policy";
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *HealthCheckPolicy) Reset() {
	*x = HealthCheckPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grape_api_core_policy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckPolicy) ProtoMessage() {}

func (x *HealthCheckPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_grape_api_core_policy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckPolicy.ProtoReflect.Descriptor instead.
func (*HealthCheckPolicy) Descriptor() ([]byte, []int) {
	return file_grape_api_core_policy_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckPolicy) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_grape_api_core_policy_proto protoreflect.FileDescriptor

var file_grape_api_core_policy_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67,
	0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x06, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x12, 0x3c, 0x0a, 0x0b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0a, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c,
	0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x17, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x10, 0x00, 0x22, 0x27, 0x0a, 0x11, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grape_api_core_policy_proto_rawDescOnce sync.Once
	file_grape_api_core_policy_proto_rawDescData = file_grape_api_core_policy_proto_rawDesc
)

func file_grape_api_core_policy_proto_rawDescGZIP() []byte {
	file_grape_api_core_policy_proto_rawDescOnce.Do(func() {
		file_grape_api_core_policy_proto_rawDescData = protoimpl.X.CompressGZIP(file_grape_api_core_policy_proto_rawDescData)
	})
	return file_grape_api_core_policy_proto_rawDescData
}

var file_grape_api_core_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grape_api_core_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grape_api_core_policy_proto_goTypes = []interface{}{
	(Policy_Type)(0),          // 0: grape.api.core.Policy.Type
	(*Policy)(nil),            // 1: grape.api.core.Policy
	(*HealthCheckPolicy)(nil), // 2: grape.api.core.HealthCheckPolicy
	(*any.Any)(nil),           // 3: google.protobuf.Any
}
var file_grape_api_core_policy_proto_depIdxs = []int32{
	0, // 0: grape.api.core.Policy.policy_type:type_name -> grape.api.core.Policy.Type
	3, // 1: grape.api.core.Policy.policy:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grape_api_core_policy_proto_init() }
func file_grape_api_core_policy_proto_init() {
	if File_grape_api_core_policy_proto != nil {
		return
	}
	file_grape_api_core_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grape_api_core_policy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grape_api_core_policy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grape_api_core_policy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grape_api_core_policy_proto_goTypes,
		DependencyIndexes: file_grape_api_core_policy_proto_depIdxs,
		EnumInfos:         file_grape_api_core_policy_proto_enumTypes,
		MessageInfos:      file_grape_api_core_policy_proto_msgTypes,
	}.Build()
	File_grape_api_core_policy_proto = out.File
	file_grape_api_core_policy_proto_rawDesc = nil
	file_grape_api_core_policy_proto_goTypes = nil
	file_grape_api_core_policy_proto_depIdxs = nil
}
