// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: grape/api/common.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MCPResourceType int32

const (
	MCPResourceType_SERVICE      MCPResourceType = 0
	MCPResourceType_POLICY       MCPResourceType = 1
	MCPResourceType_DEPLOY_GROUP MCPResourceType = 2
)

// Enum value maps for MCPResourceType.
var (
	MCPResourceType_name = map[int32]string{
		0: "SERVICE",
		1: "POLICY",
		2: "DEPLOY_GROUP",
	}
	MCPResourceType_value = map[string]int32{
		"SERVICE":      0,
		"POLICY":       1,
		"DEPLOY_GROUP": 2,
	}
)

func (x MCPResourceType) Enum() *MCPResourceType {
	p := new(MCPResourceType)
	*p = x
	return p
}

func (x MCPResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_grape_api_common_proto_enumTypes[0].Descriptor()
}

func (MCPResourceType) Type() protoreflect.EnumType {
	return &file_grape_api_common_proto_enumTypes[0]
}

func (x MCPResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPResourceType.Descriptor instead.
func (MCPResourceType) EnumDescriptor() ([]byte, []int) {
	return file_grape_api_common_proto_rawDescGZIP(), []int{0}
}

type Component_ComponentType int32

const (
	Component_PILOT    Component_ComponentType = 0
	Component_EXAUTH   Component_ComponentType = 1
	Component_LOGTRANS Component_ComponentType = 2
)

// Enum value maps for Component_ComponentType.
var (
	Component_ComponentType_name = map[int32]string{
		0: "PILOT",
		1: "EXAUTH",
		2: "LOGTRANS",
	}
	Component_ComponentType_value = map[string]int32{
		"PILOT":    0,
		"EXAUTH":   1,
		"LOGTRANS": 2,
	}
)

func (x Component_ComponentType) Enum() *Component_ComponentType {
	p := new(Component_ComponentType)
	*p = x
	return p
}

func (x Component_ComponentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Component_ComponentType) Descriptor() protoreflect.EnumDescriptor {
	return file_grape_api_common_proto_enumTypes[1].Descriptor()
}

func (Component_ComponentType) Type() protoreflect.EnumType {
	return &file_grape_api_common_proto_enumTypes[1]
}

func (x Component_ComponentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Component_ComponentType.Descriptor instead.
func (Component_ComponentType) EnumDescriptor() ([]byte, []int) {
	return file_grape_api_common_proto_rawDescGZIP(), []int{1, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grape_api_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grape_api_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grape_api_common_proto_rawDescGZIP(), []int{0}
}

type Component struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompType    Component_ComponentType `protobuf:"varint,1,opt,name=comp_type,json=compType,proto3,enum=grape.api.Component_ComponentType" json:"comp_type,omitempty"`
	Id          string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ClusterCode string                  `protobuf:"bytes,3,opt,name=cluster_code,json=clusterCode,proto3" json:"cluster_code,omitempty"`
	Host        string                  `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *Component) Reset() {
	*x = Component{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grape_api_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_grape_api_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_grape_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *Component) GetCompType() Component_ComponentType {
	if x != nil {
		return x.CompType
	}
	return Component_PILOT
}

func (x *Component) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Component) GetClusterCode() string {
	if x != nil {
		return x.ClusterCode
	}
	return ""
}

func (x *Component) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_grape_api_common_proto protoreflect.FileDescriptor

var file_grape_api_common_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xc9, 0x01, 0x0a,
	0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e,
	0x67, 0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x22, 0x34, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x49, 0x4c, 0x4f, 0x54, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x45, 0x58, 0x41, 0x55, 0x54, 0x48, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f,
	0x47, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x10, 0x02, 0x2a, 0x3c, 0x0a, 0x0f, 0x4d, 0x43, 0x50, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x4f, 0x4c, 0x49,
	0x43, 0x59, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x5f, 0x47,
	0x52, 0x4f, 0x55, 0x50, 0x10, 0x02, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grape_api_common_proto_rawDescOnce sync.Once
	file_grape_api_common_proto_rawDescData = file_grape_api_common_proto_rawDesc
)

func file_grape_api_common_proto_rawDescGZIP() []byte {
	file_grape_api_common_proto_rawDescOnce.Do(func() {
		file_grape_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_grape_api_common_proto_rawDescData)
	})
	return file_grape_api_common_proto_rawDescData
}

var file_grape_api_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grape_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grape_api_common_proto_goTypes = []interface{}{
	(MCPResourceType)(0),         // 0: grape.api.MCPResourceType
	(Component_ComponentType)(0), // 1: grape.api.Component.ComponentType
	(*Empty)(nil),                // 2: grape.api.Empty
	(*Component)(nil),            // 3: grape.api.Component
}
var file_grape_api_common_proto_depIdxs = []int32{
	1, // 0: grape.api.Component.comp_type:type_name -> grape.api.Component.ComponentType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grape_api_common_proto_init() }
func file_grape_api_common_proto_init() {
	if File_grape_api_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grape_api_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grape_api_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Component); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grape_api_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grape_api_common_proto_goTypes,
		DependencyIndexes: file_grape_api_common_proto_depIdxs,
		EnumInfos:         file_grape_api_common_proto_enumTypes,
		MessageInfos:      file_grape_api_common_proto_msgTypes,
	}.Build()
	File_grape_api_common_proto = out.File
	file_grape_api_common_proto_rawDesc = nil
	file_grape_api_common_proto_goTypes = nil
	file_grape_api_common_proto_depIdxs = nil
}
