// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: grape/api/service.proto

// import "google/protobuf/any.proto";
// import "grape/api/annotations.proto";

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service_Protocol int32

const (
	Service_HTTP  Service_Protocol = 0
	Service_HTTPS Service_Protocol = 1
	Service_HTTP2 Service_Protocol = 2
	Service_TCP   Service_Protocol = 3
	Service_UDP   Service_Protocol = 4
	Service_TLS   Service_Protocol = 5
	Service_GRPC  Service_Protocol = 6
)

// Enum value maps for Service_Protocol.
var (
	Service_Protocol_name = map[int32]string{
		0: "HTTP",
		1: "HTTPS",
		2: "HTTP2",
		3: "TCP",
		4: "UDP",
		5: "TLS",
		6: "GRPC",
	}
	Service_Protocol_value = map[string]int32{
		"HTTP":  0,
		"HTTPS": 1,
		"HTTP2": 2,
		"TCP":   3,
		"UDP":   4,
		"TLS":   5,
		"GRPC":  6,
	}
)

func (x Service_Protocol) Enum() *Service_Protocol {
	p := new(Service_Protocol)
	*p = x
	return p
}

func (x Service_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_grape_api_service_proto_enumTypes[0].Descriptor()
}

func (Service_Protocol) Type() protoreflect.EnumType {
	return &file_grape_api_service_proto_enumTypes[0]
}

func (x Service_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service_Protocol.Descriptor instead.
func (Service_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_grape_api_service_proto_rawDescGZIP(), []int{0, 0}
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// option (resource).type = "api.grape.service";
	Name            string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string           `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceProtocol Service_Protocol `protobuf:"varint,4,opt,name=service_protocol,json=serviceProtocol,proto3,enum=grape.api.Service_Protocol" json:"service_protocol,omitempty"`
	DeployGroup     []string         `protobuf:"bytes,5,rep,name=deploy_group,json=deployGroup,proto3" json:"deploy_group,omitempty"`
	Policy          []string         `protobuf:"bytes,6,rep,name=policy,proto3" json:"policy,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grape_api_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_grape_api_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_grape_api_service_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Service) GetServiceProtocol() Service_Protocol {
	if x != nil {
		return x.ServiceProtocol
	}
	return Service_HTTP
}

func (x *Service) GetDeployGroup() []string {
	if x != nil {
		return x.DeployGroup
	}
	return nil
}

func (x *Service) GetPolicy() []string {
	if x != nil {
		return x.Policy
	}
	return nil
}

var File_grape_api_service_proto protoreflect.FileDescriptor

var file_grape_api_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x72, 0x61, 0x70, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x22, 0x8f, 0x02, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x4f, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x48,
	0x54, 0x54, 0x50, 0x53, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x54, 0x54, 0x50, 0x32, 0x10,
	0x02, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44,
	0x50, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x4c, 0x53, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04,
	0x47, 0x52, 0x50, 0x43, 0x10, 0x06, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x72, 0x61, 0x70, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grape_api_service_proto_rawDescOnce sync.Once
	file_grape_api_service_proto_rawDescData = file_grape_api_service_proto_rawDesc
)

func file_grape_api_service_proto_rawDescGZIP() []byte {
	file_grape_api_service_proto_rawDescOnce.Do(func() {
		file_grape_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_grape_api_service_proto_rawDescData)
	})
	return file_grape_api_service_proto_rawDescData
}

var file_grape_api_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grape_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grape_api_service_proto_goTypes = []interface{}{
	(Service_Protocol)(0), // 0: grape.api.Service.Protocol
	(*Service)(nil),       // 1: grape.api.Service
}
var file_grape_api_service_proto_depIdxs = []int32{
	0, // 0: grape.api.Service.service_protocol:type_name -> grape.api.Service.Protocol
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grape_api_service_proto_init() }
func file_grape_api_service_proto_init() {
	if File_grape_api_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grape_api_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grape_api_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grape_api_service_proto_goTypes,
		DependencyIndexes: file_grape_api_service_proto_depIdxs,
		EnumInfos:         file_grape_api_service_proto_enumTypes,
		MessageInfos:      file_grape_api_service_proto_msgTypes,
	}.Build()
	File_grape_api_service_proto = out.File
	file_grape_api_service_proto_rawDesc = nil
	file_grape_api_service_proto_goTypes = nil
	file_grape_api_service_proto_depIdxs = nil
}
