// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Clusters         string
	Groups           string
	Namespaces       string
	Nodes            string
	SchemaMigrations string
	Services         string
}{
	Clusters:         "clusters",
	Groups:           "groups",
	Namespaces:       "namespaces",
	Nodes:            "nodes",
	SchemaMigrations: "schema_migrations",
	Services:         "services",
}
